name: logisafetygen
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.3.0=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.13.4=py312h06a4308_0
  - bleach=6.2.0=py312h06a4308_0
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2025.8.3=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - h11=0.16.0=py312h06a4308_0
  - httpcore=1.0.9=py312h06a4308_0
  - httpx=0.28.1=py312h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py312h06a4308_0
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.25.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.5=py312h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.16.0=py312h06a4308_0
  - jupyter_server_terminals=0.5.3=py312h06a4308_0
  - jupyterlab=4.4.4=py312h06a4308_0
  - jupyterlab_pygments=0.3.0=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.2=py312h06a4308_0
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.4=py312h06a4308_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - openssl=3.0.17=h5eee18b_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py312h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.4=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=78.1.1=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - urllib3=2.5.0=py312h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.12.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - anyio==4.10.0
      - backcall==0.2.0
      - banal==1.0.6
      - cached-property==2.0.1
      - charset-normalizer==3.4.2
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataset==1.6.2
      - distro==1.9.0
      - docopt==0.6.2
      - faker==37.6.0
      - filelock==3.18.0
      - fonttools==4.61.1
      - fsspec==2025.7.0
      - greenlet==3.2.4
      - hf-xet==1.1.7
      - huggingface-hub==0.34.3
      - idna==3.10
      - ipython==8.12.3
      - jiter==0.10.0
      - kernels==0.9.0
      - kiwisolver==1.4.9
      - lark==1.2.2
      - loguru==0.7.3
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==1.99.2
      - pandas==2.3.3
      - pillow==12.0.0
      - pipreqs==0.5.0
      - portkey==0.1.2
      - portkey-ai==1.14.3
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.5
      - pytz==2025.2
      - regex==2025.7.34
      - rich==14.2.0
      - safetensors==0.6.1
      - seaborn==0.13.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==1.4.54
      - stdlib-list==0.11.1
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.55.0
      - triton==3.4.0
      - typer==0.20.0
      - types-requests==2.32.4.20250809
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - websockets==15.0.1
      - werkzeug==3.1.3
      - yarg==0.1.9
